name: "token2wav"
backend: "python"
max_batch_size: 1

input [
  {
    name: "target_speech_tokens"
    data_type: TYPE_INT32
    dims: [-1]
  },
  {
    name: "prompt_speech_tokens"
    data_type: TYPE_INT32
    dims: [-1]
    optional: true
  },
  {
    name: "prompt_speech_feat"
    data_type: TYPE_FP16
    dims: [-1, 80]
    optional: true
  },
  {
    name: "prompt_spk_embedding"
    data_type: TYPE_FP16
    dims: [-1]
    optional: true
  },
  {
    name: "token_offset"
    data_type: TYPE_INT32
    dims: [1]
    reshape: { shape: [] }
    optional: true
  },
  {
    name: "finalize"
    data_type: TYPE_BOOL
    dims: [1]
    reshape: { shape: [] }
    optional: true
  }
]
output [
  {
    name: "waveform"
    data_type: TYPE_FP32
    dims: [-1]
  }
]

parameters [
  {
    key: "model_dir"
    value: {string_value: "/cosyvoice_build/CosyVoice2-0.5B"}
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
