name: "chatterbox_lm"
platform: "onnxruntime_onnx"
max_batch_size: 8

input [
  {
    name: "inputs_embeds"
    data_type: TYPE_FP32
    dims: [-1, 896]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [-1]
  },
  {
    name: "position_ids"
    data_type: TYPE_INT64
    dims: [-1]
  }
]

output [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [-1, 8195]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

optimization {
  execution_accelerators {
    gpu_execution_accelerator : [
      { name : "cuda" }
    ]
  }
}
