name: "token2wav_dit"
backend: "python"
max_batch_size: 1

input [
  {
    name: "target_speech_tokens"
    data_type: TYPE_INT32
    dims: [-1]
  },
  {
    name: "reference_wav"
    data_type: TYPE_FP32
    dims: [-1]
  },
  {
    name: "reference_wav_len"
    data_type: TYPE_INT32
    dims: [1]
  },
  {
    name: "finalize"
    data_type: TYPE_BOOL
    dims: [1]
    reshape: { shape: [] }
    optional: true
  }
]
output [
  {
    name: "waveform"
    data_type: TYPE_FP32
    dims: [-1]
  }
]

parameters [
  {
    key: "model_dir"
    value: {string_value: "/models/tts/assets"}
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
